Update base_system.yml

diff --git a/.github/workflows/base_system.yml b/.github/workflows/base_system.yml
--- a/.github/workflows/base_system.yml
+++ b/.github/workflows/base_system.yml
@@ -78,11 +78,12 @@ jobs:
       - name: MAKE ARTIFACT
         run: |
           sudo apt install --no-install-recommends --no-install-suggests xz-utils -y
-          cd "$ROOTFS_DIR" && sudo tar --use-compress-program='xz -9' -cf /tmp/rootfs_${ARCH}.tar.xz *
+          cd "$ROOTFS_DIR" && sudo tar --use-compress-program='xz -9' -cf /tmp/rootfs_debian_${CODENAME}_${ARCH}_${ROOTFS_TYPE}.tar.xz *
 
       - name: UPLOAD ARTIFACT
         run: |
           _title="${CODENAME}-${ARCH}-$ROOTFS_TYPE"
-          _resources="/tmp/rootfs_${ARCH}.tar.xz"
-          gh release delete "$_title" --cleanup-tag --yes || true
-          gh release create "$_title" $_resources --generate-notes --title "$_title" --latest=false
+          _resources="/tmp/rootfs_debian_${CODENAME}_${ARCH}_${ROOTFS_TYPE}.tar.xz"
+          # gh release delete "$_title" --cleanup-tag --yes || true
+          gh release create v1.0.0 --title "Rootfs Debian" --latest=false || true
+          gh release upload v1.0.0 $_resources --clobber
